package components

import (
  "fmt"
)

func Usage() {
  Version := "1.0.0"
  Date := "12 August 2026"
  cmd := Command()
  opt := Option()
  note := Note()
  header := Header()

  fmt.Printf( "%s is a general-purpose entrypoint\nto text analysis for digital humanists\n", cmd("gyrate"))
  fmt.Printf( "(version %s, %s)\n", Version, Date)
  fmt.Println()
  fmt.Printf("%s\n", header("## USAGE: "))
  fmt.Printf( "  %s %s [FILES]\n", cmd("gyrate"), opt("[OPTION]"))
  fmt.Println()
  fmt.Printf("  (Refer to %s for required file paths.)\n", header("PARAMETERS"))
  fmt.Println()
  fmt.Printf("%s\n", header("## GENERAL: "))
  fmt.Printf( "%s\n", opt("  --help"))
  fmt.Println("      Display this message.")
  fmt.Printf( "%s\n", opt("  --license"))
  fmt.Println("      Display the license.")
  fmt.Printf( "%s\n", opt("  --examples"))
  fmt.Println("      Display some example usages.")
  fmt.Printf("\n%s\n", header("## CLASSIFICATION: "))
  fmt.Printf( "%s %s\n", opt("  --bayes"), "[FILE] [YES_FILE] [NO_FILE]")
  fmt.Println("      Bayesian classification")
  fmt.Printf( "%s %s\n", opt("  --bayes-all"), "[DIRECTORY] [YES_FILE] [NO_FILE]")
  fmt.Println("      Parallel Bayesian classification for a directory")
  fmt.Printf( "%s %s\n", opt("  --bayes-sentence"), "[FILE] [YES_FILE] [NO_FILE]")
  fmt.Println("      Sentence-by-sentence Bayes classification of a sentence.")
  fmt.Println("      Returns CSV of format: line number, score, running score.")
  fmt.Printf( "%s %s\n", opt("  --logistic"), "[FILE]")
  fmt.Println("      Logistic regression")
  fmt.Printf( "%s %s\n", opt("  --logistic-all"), "[DIRECTORY]")
  fmt.Println("      Logistic regression on a directory")
  fmt.Printf( "%s %s\n", opt("  --logistic-rebuild"), "[YES_FILE] [NO_FILE]")
  fmt.Println("      Rebuild model for logistic regression\n      (allows parallelization)")
  fmt.Printf( "%s %s\n", opt("  --embed"), "[DIRECTORY] [QUERY]")
  fmt.Println("      Semantic search")
  fmt.Printf( "%s %s\n", opt("  --embed-rebuild"), "[DIRECTORY] [QUERY]")
  fmt.Println("      Rebuild model for semantic search")
  fmt.Printf( "%s %s\n", opt("  --dependency"), "[DIRECTORY] [DB] [TABLE] [TERM]")
  fmt.Println("      Return a structured list of verbs associated\n      with a given noun term.")
  fmt.Printf( "%s %s\n", opt("  --year-bridge"), "[DB] [TABLE]")
  fmt.Printf( "      %s. If the DB has both a YEAR\n", note("For use in pipes"))
  fmt.Println("      and an ORIGINAL_ID parameter, inserts the YEAR")
  fmt.Println("      between the ID and the VALUE.")
  fmt.Printf( "%s %s\n", opt("  --duplicates"), "[DIRECTORY]")
  fmt.Println("      Return a csv of duplicate files in a directory.")
  fmt.Printf( "%s %s\n", opt("  --normalize"), "[CSV] [MINIMUM?] [MAXIMUM?]")
  fmt.Println("      Return a normalized csv for comparison purposes.\n      Can be redirected into a file or piped.")
  fmt.Println()
  fmt.Printf("%s\n", header("## PARAMETERS:"))
  fmt.Println("  FILE     : The file that is being classified.")
  fmt.Println("  YES_FILE : One of the classification categories,")
  fmt.Println("             preferably a positive one.")
  fmt.Println("  NO_FILE  : Ditto for negative.")
  fmt.Println("  DIRECTORY: A directory of files to be classified.")
  fmt.Println("  DB       : A SQL database.")
  fmt.Println("  TABLE    : A table name in the SQL database.")
  fmt.Println("  QUERY    : A word, or a quoted string, that the")
  fmt.Println("             program attempts to semantically match.")
  fmt.Println("  TERM     : A single noun or a text file containing")
  fmt.Println("             nouns, each separated by a newline.")
  fmt.Println("  MINIMUM? : Optional. A minimum value to normalize to.")
  fmt.Println("  MAXIMUM? : Optional. Ditto maximum.")
  fmt.Println()
}
