#!/usr/bin/env bash

if [[ $# -lt 2 || $1 == "-h" || $2 == "-h" || $1 == $2 ]]; then
  echo "difference:"
  echo "  displays numeric differences between two"
  echo "  CSV files created by gyrate"
  echo ""
  echo "Usage:"
  echo "  difference CSV CSV"
  echo ""
  echo "Example:"
  echo "  If we have two CSVs that look like this:"
  echo "  ╔════╦═══════╗  ╔════╦═══════╗ "
  echo "  ║ id ║ value ║  ║ id ║ value ║ "
  echo "  ╠════╬═══════╣  ╠════╬═══════╣ "
  echo "  ║ A  ║   1   ║  ║ A  ║   2   ║ "
  echo "  ╚════╩═══════╝  ╚════╩═══════╝ "
  echo " Would result in a CSV to the effect of:"
  echo "  ╔════╦═══════╗ "
  echo "  ║ id ║ value ║ "
  echo "  ╠════╬═══════╣ "
  echo "  ║ A  ║   -1  ║ "
  echo "  ╚════╩═══════╝ "
  exit 1
fi
xan join 0 $1 0 $2                          |
xan rename -n 'col(0),col(1),col(2),col(3)' |
xan sort -s 0                               |
xan drop 'col(2)'                           |
xan map 'col(1) - col(2)'                   |
xan drop 1                                  |
xan drop 1                                  |
xan rename 'id,difference'                  |
xan sort -s difference
